name: CI

on:
  push:
    branches:
      - '*'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
            cache: 'npm'

      - name: Run install dependencies
        run: npm install

      - name: Run test
        run: npm run test:ci

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  vercel:
    name: Vercel Action
    runs-on: ubuntu-latest
    needs: sonarcloud
    
    steps:
      - uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
